# Meta
site_name: J's Software Development Pages
site_url: https://joostvdg.github.io
# Copyright
copyright: 'Copyright &copy; 2022 Joost van der Griendt'
repo_name: 'joostvdg/joostvdg.github.io'
repo_url: 'https://github.com/joostvdg/joostvdg.github.io'

docs_dir: 'docs'

nav:
- Home: 
  - Me: index.md
  - MKDocs (This Static Website): other/mkdocs.md
  - VIM: other/vim.md
  - Shell: other/shell.md
- Blogs:
  - Jenkins Pipeline Support Tools: blogs/jenkins-pipeline-support-tool.md
  - Docker Graceful Shutdown: blogs/graceful-shutdown.md
  # - GitOps Pipeline: blogs/gitops-pipeline.md
  - Pipelines with Docker Alternatives: blogs/docker-alternatives.md
  # - Create your own k8s controller: blogs/k8s-controller.md
  - Let's Encrypt for Kubernetes Apps: blogs/k8s-lets-encrypt.md
  - CloudBees SSO Azure AD: blogs/sso-azure-ad.md
  - CloudBees Automate Teams: blogs/teams-automation.md
  - Kubernetes SSO Keycloak: blogs/kubernetes-sso-keycloak.md
  - Jenkins X Java Native Image Prod: 
    - Intro: jenkinsx/java-native-prod/01-intro.md
    - Cloud SQL: jenkinsx/java-native-prod/02-cloud-sql.md
    - Quarkus: jenkinsx/java-native-prod/03-quarkus.md
    - Import Into Jenkins X: jenkinsx/java-native-prod/04-jx-import.md
    - Database Connection And Secrets: jenkinsx/java-native-prod/05-jx-secrets.md
    - Native Image: jenkinsx/java-native-prod/06-native-image.md
    - Pipeline Improvements: jenkinsx/java-native-prod/07-pipeline-improvements.md
    - Previews & Integration Tests: jenkinsx/java-native-prod/08-preview-int-test.md
    - Production Improvements: jenkinsx/java-native-prod/09-production-improvements.md
    - Promote To Production: jenkinsx/java-native-prod/10-promote-prod.md
  - Jenkins Monitoring Kubernetes: 
    - Introduction: blogs/monitor-jenkins-on-k8s/introduction.md
    - Prepare Environment: blogs/monitor-jenkins-on-k8s/prepare.md
    - Install Tools: blogs/monitor-jenkins-on-k8s/install.md
    - Metrics: blogs/monitor-jenkins-on-k8s/metrics.md
    - Alerts: blogs/monitor-jenkins-on-k8s/alerts.md
    - Pipeline: blogs/monitor-jenkins-on-k8s/pipeline.md
    - Dashboard: blogs/monitor-jenkins-on-k8s/dashboard.md
    - CloudBees: blogs/monitor-jenkins-on-k8s/cloudbees.md
  - Create your own k8s resource: blogs/k8s-crd.md
  - DockerCon EU 2018: blogs/dockercon-eu-2018.md
- Jenkins & CloudBees:
  # - SDM:
  #   - What Is SDM: sdm/what-is-sdm.md
  #   - SDM Platform Anatomy: sdm/platform-anatomy.md
  - Jenkins On Kubernetes: jenkins/jenkins-on-kubernetes.md
  - TAP & Jenkins: tanzu/jenkins-tap.md
  - CloudBees:
    # - CloudBees Previews: cloudbees/cb-previews.md
    - CloudBees CasC: cloudbees/cbci-casc.md
    - Single Sign On - AzureAD: cloudbees/sso-azure-ad.md
    - CloudBees Automate Teams: cloudbees/teams-automation.md
    - CloudBees CI on GKE: cloudbees/cbc-gke-helm.md
    - CloudBees CI on EKS: cloudbees/cbc-eks.md
    - Team Master Namespace: cloudbees/cbc-team-namespace.md
    - Multi-Cluster GKE: cloudbees/multi-cluster-gke.md
    - Multi-Cluster EKS: cloudbees/multi-cluster-eks.md
    - Multi-Cluster (OLD/AKS): cloudbees/multi-cluster.md
  - Jenkins: 
    - Intro: jenkins/index.md
    - JobDSL: jenkins-jobs/jobdsl.md
    - JenkinsJobsBuilder: jenkins-jobs/jenkins-jobs-builder.md
  - Jenkins Pipelines:
    - Job Types: jenkins-pipeline/job-types.md
    - Build Docker Image Kaniko: jenkins-pipeline/kaniko-pipelines.md
    - PodTemplate With Docker-In-Docker: jenkins-pipeline/podtemplate-dind.md
    - Parallel Pipelines: jenkins-pipeline/jenkins-parallel-pipeline.md
    - Core Concepts: jenkins-pipeline/core-concepts.md
    - Artifactory Integration: jenkins-pipeline/artifactory-integration.md
    - Pipeline (declarative): jenkins-pipeline/declarative-pipeline.md
    - Groovy DSL Pipeline: jenkins-pipeline/groovy-pipeline.md
    - Pipeline Libraries: jenkins-pipeline/global-shared-library.md
    - DSL IDE Integration: jenkins-pipeline/ide-integration-pipeline-dsl.md
    - Input: jenkins-pipeline/input.md
  - Jenkins Pipeline Examples:
    - Index: jenkins-pipeline-examples/index.md
    - Docker Alternatives: jenkins-pipeline-examples/docker-alternatives.md
    - Maven Declarative: jenkins-pipeline-examples/maven-declarative.md
    - Docker Declarative: jenkins-pipeline-examples/docker-declarative.md

- Kubernetes & Docker:
  - OpenShift:
    - OpenShift 3.11 GCP(minimal): openshift/rhos311-gcp-minimal.md
    - OpenShift 3.11 GCP(medium): openshift/rhos311-gcp-medium.md
  - Kubernetes (K8S):
    - Introduction: kubernetes/index.md
    - CKA Exam prep: kubernetes/cka-exam-prep.md
    - Tools: kubernetes/tools.md
  - Managed Kubernetes (cloud):
    - GKE: kubernetes/distributions/install-gke.md
    - GKE Terraform: kubernetes/distributions/gke-terraform.md
    - AWS EKS: kubernetes/distributions/eks-eksctl.md
    - AKS CLI : kubernetes/distributions/aks-cli.md
    - AKS Terraform : kubernetes/distributions/aks-terraform.md
  - K8S Hard Way - GCE:
    - Installer Preparation: kubernetes/khw-gce/index.md
    - Create GCE resources: kubernetes/khw-gce/terraform-compute.md
    - Prepare Certificates: kubernetes/khw-gce/certificates.md 
    - Prepare Kubeconfigs: kubernetes/khw-gce/kubeconfigs.md
    - Encryption configuration: kubernetes/khw-gce/encryption.md
    - ETCD configuration: kubernetes/khw-gce/etcd.md
    - Controller Config: kubernetes/khw-gce/controller.md
    - Worker Config: kubernetes/khw-gce/worker.md
    - Remote access: kubernetes/khw-gce/remote-access.md
    - Network config: kubernetes/khw-gce/network.md
    - Debug: kubernetes/khw-gce/debug.md
  - Docker:
    - Graceful Shutdown: docker/graceful-shutdown.md
    - BuildKit: docker/build-kit.md
    - Multi-Stage Builds(TBD): docker/multi-stage-builds.md
    - Swarm (mode) (TBD): docker/swarm.md
  - Linux:
    - SystemD: linux/systemd.md
- VMware Tanzu:
  - Tanzu: tanzu/index.md
  - TAP on TKGs: tanzu/tap-on-tkgs.md
  - Harbor with custom CA: tanzu/harbor-ca.md
  - TAP Jenkins: tanzu/jenkins-tap.md
  - TKG Grafana with LDAP: tanzu/tkg-grafana.md
  - Dependencies: tanzu/dependencies.md
- Jenkins X: 
  - Build Packs: jenkinsx/build-packs.md
  - Jenkins X Pipelines: jenkinsx/jx-pipelines.md
  - Java Native Image Prod: 
    - Intro: jenkinsx/java-native-prod/01-intro.md
    - Cloud SQL: jenkinsx/java-native-prod/02-cloud-sql.md
    - Quarkus: jenkinsx/java-native-prod/03-quarkus.md
    - Import Into Jenkins X: jenkinsx/java-native-prod/04-jx-import.md
    - Database Connection And Secrets: jenkinsx/java-native-prod/05-jx-secrets.md
    - Native Image: jenkinsx/java-native-prod/06-native-image.md
    - Pipeline Improvements: jenkinsx/java-native-prod/07-pipeline-improvements.md
    - Previews & Integration Tests: jenkinsx/java-native-prod/08-preview-int-test.md
    - Production Improvements: jenkinsx/java-native-prod/09-production-improvements.md
    - Promote To Production: jenkinsx/java-native-prod/10-promote-prod.md
  - Create Builder Image: jenkinsx/builder-image.md
  - JX Boot GKE: jenkinsx/jxboot.md
  - JX Boot AKS: jenkinsx/jxboot-aks.md
  - JX Boot & CloudBees Core: jenkinsx/aks-boot-core.md
  - OpenShift 3.11: jenkinsx/rhos-311-minimal.md
  - OpenShift 3.11 - Restricted: jenkinsx/rhos-311-restricted.md
  - Lighthouse & Bitbucket: jenkinsx/lighthouse-bitbucket.md
  - HelloWorld: jenkinsx/hello-world.md
  - Maven: jenkinsx/maven.md
  - Hybrid: jenkinsx/hybrid.md
  - Example For Console Reel: jenkinsx/kubernetes-days.md    
- Software Eng.:
  - Automation:
    - Pulumi: cloud/automation-pulumi.md
    - Let's Encrypt K8S: certificates/lets-encrypt-k8s.md
  - Software Engineering:
    - Important Concepts: swe/important-concepts.md
    - Naming: swe/naming.md
    # - Domain Driven Design: swe/ddd.md
    # - Microservices: swe/microservices.md
    # - Algorithms: swe/algorithms.md
    # - Observability: swe/observability.md
    - Distributed Computing: swe/distributed.md
    # - Others: swe/others.md
  - Productivity:
    - General: productivity/index.md
    - Incidents: productivity/incidents.md
    # - Tools: productivity/tools.md
    # - Intelli J: productivity/intellij.md
    # - Paradigms: productivity/paradigms.md
    # - Studies: productivity/studies.md
  - Java:
    - General: java/index.md
    - Spring Boot App: keep-watching/
    # - Spring Boot: java/spring/boot.md
    # - Java Modules: java/java-modules.md
    # - Java Ecosystem: java/ecosystem.md
    - Java Networking: java/networking.md
    # - Java Streams: java/streams.md
    - Java Concurrency: java/concurrency.md


# Theme
# Configuration
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - content.code.annotate
    - toc.follow
  name: material
  language: 'en'
  icon:
    logo: material/cloud
  palette:
    # - primary: 'orange'
    # - accent: 'indigo'
    - scheme: default
      primary: 'orange'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate # 
      primary: 'deep orange'
      accent: 'teal'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

plugins:
  - tags
  - git-revision-date-localized:
      type: iso_datetime
  - search
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-353607268
  disqus: 'joostvdg-github-io'
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/joostvdg
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joost_vdg
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/joostvdg

# Extensions
markdown_extensions:
  - abbr
  - footnotes
  - admonition
  - codehilite:
      linenums: true
      guess_lang: true
  - meta
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

